### ISSUE TITLE
When other players join the world, the screen freezes for a few seconds.

### ISSUE THREAD

**Issue by kvroha** [SaphieNyako/Feywild#37] opened 2021-10-23 16:25 UTC
When JEI is installed on the client, every time a player joins the world, the screen of other players will freeze for a few seconds.

Thanks for any help, I like this mod very much.

**Comment by SaphieNyako** [comment] 2021-10-23 16:35
Hello. What makes you conclude it's caused by our mod? Do you have extra info? What other mods are used?

**Comment by SaphieNyako** [comment] 2021-10-23 17:11
We tested it on our own server with JEI and feywild. 
And we didnt find any issues, nor as experiencing a freeze in game. 
Or the log showing something is wrong or loading.

Do you perhaps have the latest log for us?

**Comment by kvroha** [comment] 2021-10-23 17:37
This problem occurs when JEI and Feywild exist on my client at the same time.
I tested it in three modpacks:

Modpack 1: Forge:36.2.8, Optifine: HD_U_G8
mod list:
Feywild-1.16.5-2.0.2
geckolib-forge-1.16.5-3.0.45
Patchouli-1.16.4-53.1
LibX-1.16.3-1.0.76
Jade-1.16.4-2.7.4
jei-1.16.5-7.7.1.126
WAWLA-1.16.5-8.0.1

When other players join the game, the screen freezes only for about 0.2 seconds, very inconspicuous.
But when I add more mods in the modpack, just like the following.

Modpack 2: Forge:36.2.8, Optifine: HD_U_G8
mod list:
Feywild-1.16.5-2.0.2
geckolib-forge-1.16.5-3.0.45
Patchouli-1.16.4-53.1
LibX-1.16.3-1.0.76
Jade-1.16.4-2.7.4
jei-1.16.5-7.7.1.126
WAWLA-1.16.5-8.0.1
-----new add------
jeiintegration_1.16.5-7.0.1.15
JustEnoughProfessions-1.16.5-1.2.1
JustEnoughResources-1.16.3-0.12.0.100

The screen freezes increased to about 1 seconds.
When I delete either JEI or Feywild, the freeze disappears.

Then I add Feywild and JEI to other modpacks, the more the mod is used, the more noticeable the freeze. The freeze can become 2-3s in a 100+ mods modpack. 
It seems that every time other players join, they will be loaded as if they came around.

**Comment by SaphieNyako** [comment] 2021-10-23 17:38
do you have to log from the moment it freezes?

**Comment by SaphieNyako** [comment] 2021-10-23 17:47
The problem is that this is sending to all players: https://github.com/SaphieNyako/Feywild/blob/2.0/src/main/java/com/feywild/feywild/EventListener.java#L93

Might have found the issue....

**Comment by SaphieNyako** [comment] 2021-10-23 17:48
Noeppi made a fix. Gonna test it and will be released in a patch :)

**Comment by kvroha** [comment] 2021-10-23 18:02
Brillant! This mod brings Real Magic to Minecraft!

**Comment by SaphieNyako** [comment] 2021-10-23 18:16
Thank you for reporting. The new version is out. Will you let us know if it made a difference?

**Comment by kvroha** [comment] 2021-10-23 18:31
This bug has been fixed, thank you!

**Comment by SaphieNyako** [comment] 2021-10-23 18:32
Thank you too !

**Closed as completed by SaphieNyako** 2021-10-23 18:32 UTC
Labels: bug, fixed in next version
